### ISSUE TITLE
IndentationError in model.py

### ISSUE THREAD

**Issue by cclauss** [wannabeOG/Mask-RCNN#1]
Python 3 treats IndentationErrors as syntax errors

flake8 testing of https://github.com/wannabeOG/Mask-RCNN on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./model.py:1255:4: E999 IndentationError: unindent does not match any outer indentation level
   .
   ^
1     E999 IndentationError: unindent does not match any outer indentation level
1
```

**Comment by DNNinfo** [comment]
@cclauss  you may delete the line to fix this problem
