### ISSUE TITLE
No module named 'nms._ext'

### ISSUE THREAD

**Issue by bruceyang2012** [wannabeOG/Mask-RCNN#6]
Could you help me with this problem?

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5b86c3896cc6> in <module>()
     17 from config import Config
     18 import utils
---> 19 import model as modellib
     20 import visualize
     21 from model import log

~/cell_seg/Mask-RCNN/codes/model.py in <module>()
     15 import utils
     16 import visualize
---> 17 from nms.nms_wrapper import nms
     18 from roialign.roi_align.crop_and_resize import CropAndResizeFunction
     19 

~/cell_seg/Mask-RCNN/codes/nms/nms_wrapper.py in <module>()
      9 from __future__ import print_function
     10 
---> 11 from nms.pth_nms import pth_nms
     12 
     13 

~/cell_seg/Mask-RCNN/codes/nms/pth_nms.py in <module>()
      1 import torch
----> 2 from ._ext import nms
      3 import numpy as np
      4 
      5 def pth_nms(dets, thresh):

ModuleNotFoundError: No module named 'nms._ext'

**Comment by bruceyang2012** [comment]
I have solved this problem, thanks.

**Comment by tclikang** [comment]
> I have solved this problem, thanks.

How did you solve it?Thanks

**Comment by zhupan007** [comment]
How did you solve it?Thanks  too

**Comment by WWaynee** [comment]
How did you solve it?Thanks too too

**Comment by buzaev-fedor** [comment]
How did you solve it?Thanks too too too
